Alqueidaozinho_House1_MapScripts::
	.byte 0


Alqueidaozinho_House1_NpcOldMan::
# 4 "data/maps/Alqueidaozinho_House1/scripts.pory"
	lock
# 5 "data/maps/Alqueidaozinho_House1/scripts.pory"
	faceplayer
# 6 "data/maps/Alqueidaozinho_House1/scripts.pory"
	msgbox Alqueidaozinho_House1_NpcOldManText
# 7 "data/maps/Alqueidaozinho_House1/scripts.pory"
	waitmessage
# 8 "data/maps/Alqueidaozinho_House1/scripts.pory"
	release
	end


Alqueidaozinho_House1_NpcOldLady::
# 13 "data/maps/Alqueidaozinho_House1/scripts.pory"
	lock
# 14 "data/maps/Alqueidaozinho_House1/scripts.pory"
	faceplayer
# 15 "data/maps/Alqueidaozinho_House1/scripts.pory"
	msgbox Alqueidaozinho_House1_NpcOldLadyText
# 16 "data/maps/Alqueidaozinho_House1/scripts.pory"
	waitmessage
# 17 "data/maps/Alqueidaozinho_House1/scripts.pory"
	release
	end


Alqueidaozinho_House1_NpcOldManText::
# 21 "data/maps/Alqueidaozinho_House1/scripts.pory"
	.string "It's almost time for Grepa berry harvest\n"
	.string "season. But you young folk don't give a\l"
	.string "Rattata's ass. You should help out more!\n$"

Alqueidaozinho_House1_NpcOldLadyText::
# 27 "data/maps/Alqueidaozinho_House1/scripts.pory"
	.string "There honey, don't get so riled up.\n"
	.string "I will make you some ginger tea.\n$"
