gText_Birch_Welcome::
	.string "Hello and welcome!\p"
	.string "You can call me GRANDMA, because… \p"
	.string "Well, that is what I am to you.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is inhabited by\n"
	.string "creatures called POKEMON!\p"
	.string "For some people, POKEMON are pets\n"
	.string "and fetch their newspaper or slippers.\l"
	.string "Others use them for battle.\p"
	.string "Myself… I am a retired POKEMON TRAINER.\n"
	.string "I was pretty badass back in my day!\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Now, about you… It is rude to assume\n"
	.string "these days, so I will ask.\p"
	.string "$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"


gText_Birch_WhatsYourName::
	.string "Oh dear, you are! I knew that,\n"
	.string "of course. You got your mother’s eyes!\p"
	.string "So, erm… What was your name again?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"
  

gText_Birch_YourePlayer::
	.string "Right!\p"
	.string "So your name is {PLAYER}{KUN}!\n"
	.string "Sorry, I need to restock my dementia\l"
	.string "pills.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "{PLAYER}{KUN}, your very own legendary\n"
	.string "journey in the RAMTO region is about to\l"
	.string "unfold!\p"
	.string "A world of dreams and adventures with\n"
	.string "POKEMON awaits!\p"
	.string "Get 'em, sugar!\p"
	.string "$"
