Alqueidaozinho_MapScripts::
	.byte 0


Alqueidaozinho_NpcWoman::
# 4 "data/maps/Alqueidaozinho/scripts.pory"
	lock
# 5 "data/maps/Alqueidaozinho/scripts.pory"
	faceplayer
# 6 "data/maps/Alqueidaozinho/scripts.pory"
	msgbox Alqueidaozinho_NpcWomanText
# 7 "data/maps/Alqueidaozinho/scripts.pory"
	waitmessage
# 8 "data/maps/Alqueidaozinho/scripts.pory"
	release
	end


Alqueidaozinho_NpcLittleBoy::
# 13 "data/maps/Alqueidaozinho/scripts.pory"
	lock
# 14 "data/maps/Alqueidaozinho/scripts.pory"
	faceplayer
# 15 "data/maps/Alqueidaozinho/scripts.pory"
	msgbox Alqueidaozinho_NpcLittleBoyText
# 16 "data/maps/Alqueidaozinho/scripts.pory"
	waitmessage
# 17 "data/maps/Alqueidaozinho/scripts.pory"
	release
	end


Alqueidaozinho_NpcOldMan::
# 22 "data/maps/Alqueidaozinho/scripts.pory"
	lock
# 23 "data/maps/Alqueidaozinho/scripts.pory"
	faceplayer
# 24 "data/maps/Alqueidaozinho/scripts.pory"
	msgbox Alqueidaozinho_NpcOldManText
# 25 "data/maps/Alqueidaozinho/scripts.pory"
	waitmessage
# 26 "data/maps/Alqueidaozinho/scripts.pory"
	release
	end


Alqueidaozinho_Sign::
# 31 "data/maps/Alqueidaozinho/scripts.pory"
	lock
# 32 "data/maps/Alqueidaozinho/scripts.pory"
	msgbox Alqueidaozinho_SignText
# 33 "data/maps/Alqueidaozinho/scripts.pory"
	waitmessage
# 34 "data/maps/Alqueidaozinho/scripts.pory"
	release
	end


Alqueidaozinho_NpcWomanText::
# 37 "data/maps/Alqueidaozinho/scripts.pory"
	.string "Did you get a Pokemon? Your mom must be\n"
	.string "proud!\p"
	.string "Oh, you don't have a mom?\n"
	.string "Oops, my bad...\n$"

Alqueidaozinho_NpcLittleBoyText::
# 44 "data/maps/Alqueidaozinho/scripts.pory"
	.string "My mom is a bit rude sometimes.\n$"

Alqueidaozinho_NpcOldManText::
# 48 "data/maps/Alqueidaozinho/scripts.pory"
	.string "There's an Arceus damned Zorua messing\n"
	.string "up our crops every now and then.\p"
	.string "I wish someone dealt with that pesky\n"
	.string "thing before I turn it into a fur coat.\n$"

Alqueidaozinho_SignText::
# 55 "data/maps/Alqueidaozinho/scripts.pory"
	.string "Grepa berry harvest season is here!\n$"
