Route04_MrDiamondHouse_MapScripts::
	.byte 0


Route04_MrDiamondHouse_EventScript_MrDiamond::
# 4 "data/maps/Route04_MrDiamondHouse/scripts.pory"
	lock
# 5 "data/maps/Route04_MrDiamondHouse/scripts.pory"
	faceplayer
# 6 "data/maps/Route04_MrDiamondHouse/scripts.pory"
	msgbox Route04_MrDiamondHouse_MrDiamondText
# 7 "data/maps/Route04_MrDiamondHouse/scripts.pory"
	waitmessage
# 8 "data/maps/Route04_MrDiamondHouse/scripts.pory"
	release
	end


Route04_MrDiamondHouse_MrDiamondText::
# 12 "data/maps/Route04_MrDiamondHouse/scripts.pory"
	.string "{COLOR BLUE}{SHADOW LIGHT_BLUE} Mr Diamond: {COLOR DARK_GRAY}{SHADOW LIGHT_GRAY}BURP\n"
	.string "Scuse me, just started my day drinking.\p"
	.string "Hm? I’ll fix your grandpa’s truck when\n"
	.string "I feel like it. If you don’t like it,\l"
	.string "you can kiss my ass.\n$"
