FlintTown_House2_MapScripts::
	.byte 0


FlintTown_House2_EventScript_Woman::
# 4 "data/maps/FlintTown_House2/scripts.pory"
	lock
# 5 "data/maps/FlintTown_House2/scripts.pory"
	faceplayer
# 6 "data/maps/FlintTown_House2/scripts.pory"
	msgbox FlintTown_House2_WomanText
# 7 "data/maps/FlintTown_House2/scripts.pory"
	waitmessage
# 8 "data/maps/FlintTown_House2/scripts.pory"
	release
	end


FlintTown_House2_EventScript_LittleGirl::
# 22 "data/maps/FlintTown_House2/scripts.pory"
	lock
# 23 "data/maps/FlintTown_House2/scripts.pory"
	faceplayer
# 24 "data/maps/FlintTown_House2/scripts.pory"
	msgbox FlintTown_House2_LittleGirlText
# 25 "data/maps/FlintTown_House2/scripts.pory"
	waitmessage
# 26 "data/maps/FlintTown_House2/scripts.pory"
	release
	end


FlintTown_House2_EventScript_LittleBoy::
# 36 "data/maps/FlintTown_House2/scripts.pory"
	lock
# 37 "data/maps/FlintTown_House2/scripts.pory"
	faceplayer
# 38 "data/maps/FlintTown_House2/scripts.pory"
	msgbox FlintTown_House2_LittleBoyText
# 39 "data/maps/FlintTown_House2/scripts.pory"
	waitmessage
# 40 "data/maps/FlintTown_House2/scripts.pory"
	release
	end


FlintTown_House2_WomanText::
# 12 "data/maps/FlintTown_House2/scripts.pory"
	.string "Long ago, RAMTO was protected by the\n"
	.string "Order of the Hetra Knights, aided by the\l"
	.string "Legendary Beast Warriors.\p"
	.string "We were unstoppable back then! Until\n"
	.string "Heatran went berserk and set fire to\l"
	.string "everything…That was the Red Ages.\n$"

FlintTown_House2_LittleGirlText::
# 30 "data/maps/FlintTown_House2/scripts.pory"
	.string "Zamazenta is the one who looks like a\n"
	.string "shield. It's the bravest!\n$"

FlintTown_House2_LittleBoyText::
# 44 "data/maps/FlintTown_House2/scripts.pory"
	.string "Zacian is the one who has a sword.\n"
	.string "It’s the coolest!\n$"
